import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'quick-start',
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'doc', id: 'developer-docs/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer-docs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      link: { type: 'doc', id: 'recipes/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'recipes',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorial',
      link: { type: 'doc', id: 'tutorial/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: 'Admin Manual',
      link: { type: 'doc', id: 'admin-docs/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'admin-docs',
        },
      ],
    },
  ],
};

export default sidebars;
